backend:
  name: github
  repo: ducdev/palettes
media_folder: static/assets
public_folder: /assets
collections:
  - name: palette
    label: Palette
    folder: palette
    create: true
    fields:
      - { name: id, label: ID, widget: ncw-id}
      - { name: colors, label: Colors, widget: list, default: [] }
      - { name: liked, label: Liked, widget: hidden, default: 0 }
